name: trading-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - ruff
    - pytest
    - ray
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - jupyter
    - black
    - flake8
    - python-dotenv
    - requests
    - pydantic
    - fastapi
    - uvicorn
    - psycopg2-binary
    - kafka-python
    - prometheus-client