name: trading-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytest
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - black
  - requests
  - python-dateutil
  - pip:
    - ruff
    - ray
    - flake8
    - python-dotenv
    - pydantic
    - fastapi
    - uvicorn
    - psycopg2-binary
    - kafka-python
    - prometheus-client
    - jquantsapi