name: trading-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytest
  - pandas
  - numpy
  - requests
  - python-dateutil
  - pip:
    - ruff
    - psycopg2-binary
    - jquantsapi